import type { BlogArticle } from './types';

export const articlesGoogleIndexing: BlogArticle[] = [
  {
    slug: 'google-not-indexing-pages',
    title: '\u201CDiscovered \u2013 Currently Not Indexed\u201D: Why Google Ignores Your Pages',
    metaTitle: 'Fix "Discovered - Currently Not Indexed" in Search Console | SEO Audit Pro',
    metaDescription: 'Google found your pages and chose not to index them. It\u2019s the most frustrating status in Search Console. Here\u2019s what it really means and the fixes that work.',
    keywords: ['discovered currently not indexed', 'Google indexing issues', 'crawled not indexed', 'Search Console', 'crawl budget'],
    category: 'Google & Indexing',
    date: '2025-01-22',
    readTime: '7 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'Google knows your page exists. It just doesn\u2019t think it\u2019s worth crawling yet. That stings, but it\u2019s fixable once you understand what the status is really telling you.',
    content: '',
  },
  {
    slug: 'mobile-first-indexing-issues',
    title: 'Mobile-First Indexing Problems That Are Costing You Rankings',
    metaTitle: 'Mobile-First Indexing Issues & Fixes: Complete Guide | SEO Audit Pro',
    metaDescription: 'Google now indexes exclusively with a mobile crawler. If your mobile page hides content, blocks resources, or lags, your rankings pay for it. Find and fix the gaps.',
    keywords: ['mobile-first indexing', 'mobile SEO', 'mobile usability', 'responsive design SEO', 'mobile rankings'],
    category: 'Google & Indexing',
    date: '2025-01-10',
    readTime: '6 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'Googlebot is a phone now. Full stop. Whatever your mobile visitors can\u2019t see, Google can\u2019t rank, and plenty of "responsive" sites still hide half their value on small screens.',
    content: '',
  },
  {
    slug: 'recover-google-core-update',
    title: 'Surviving Google Core Updates: What to Do When Your Traffic Tanks',
    metaTitle: 'Google Core Update Recovery: A Realistic Action Plan | SEO Audit Pro',
    metaDescription: 'Traffic dropped 40% overnight after a Google core update? Here\u2019s a realistic recovery framework: how to diagnose the hit, what to fix, and what timeline to expect.',
    keywords: ['Google core update', 'traffic drop recovery', 'algorithm update', 'helpful content', 'SEO recovery'],
    category: 'Google & Indexing',
    date: '2024-12-15',
    readTime: '7 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'A core update hit and your charts fell off a cliff. Before you panic-delete half your site or buy a "recovery service," read this. Recovery is real, but it doesn\u2019t work how most people think.',
    content: '',
  },
];
