import type { BlogArticle } from './types';

export const articlesCoreWebVitals: BlogArticle[] = [
  {
    slug: 'inp-core-web-vital-fix',
    title: 'INP Is the Core Web Vital Nobody Prepared For (Here\u2019s How to Fix It)',
    metaTitle: 'How to Fix INP (Interaction to Next Paint) in 2025 | SEO Audit Pro',
    metaDescription: 'INP replaced FID as a Core Web Vital in March 2024 and thousands of sites failed overnight. Learn what Interaction to Next Paint measures and how to get under 200ms.',
    keywords: ['INP', 'Interaction to Next Paint', 'Core Web Vitals', 'fix INP', 'INP optimization'],
    category: 'Core Web Vitals',
    date: '2025-01-14',
    readTime: '6 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'When Google swapped FID for INP in March 2024, sites that passed Core Web Vitals for years suddenly started failing. Here\u2019s why, and what you can actually do about it.',
    content: '',
  },
  {
    slug: 'fix-largest-contentful-paint',
    title: 'How to Actually Fix Largest Contentful Paint (LCP) in 2025',
    metaTitle: 'Fix Largest Contentful Paint (LCP): Practical Guide | SEO Audit Pro',
    metaDescription: 'LCP under 2.5 seconds is the target, yet most sites miss it. A practical, no-fluff guide to diagnosing and fixing slow LCP: images, TTFB, render delay and more.',
    keywords: ['LCP', 'Largest Contentful Paint', 'fix LCP', 'Core Web Vitals', 'page speed'],
    category: 'Core Web Vitals',
    date: '2025-01-08',
    readTime: '7 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'Everyone tells you to "optimize images" and calls it a day. Real LCP fixes go deeper. Here\u2019s the diagnostic process we use on actual client sites.',
    content: '',
  },
  {
    slug: 'fix-cumulative-layout-shift',
    title: 'Cumulative Layout Shift: Why Your Page Jumps Around and How to Stop It',
    metaTitle: 'Fix Cumulative Layout Shift (CLS): Complete Guide | SEO Audit Pro',
    metaDescription: 'Buttons that move as you click, text that jumps mid-read. CLS ruins user experience and rankings. Learn the real causes of layout shift and how to get under 0.1.',
    keywords: ['CLS', 'Cumulative Layout Shift', 'layout shift fix', 'Core Web Vitals', 'web performance'],
    category: 'Core Web Vitals',
    date: '2024-12-19',
    readTime: '6 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'You go to tap a link and an ad shoves it down the page at the last second. That\u2019s layout shift, Google measures it, and your site probably has more of it than you think.',
    content: '',
  },
];
