import type { BlogArticle } from './types';

export const articlesPageSpeed: BlogArticle[] = [
  {
    slug: 'pagespeed-lab-vs-field-data',
    title: 'Why Your PageSpeed Score Doesn\u2019t Match Real User Experience',
    metaTitle: 'PageSpeed Score vs Real User Data: Lab vs Field Explained | SEO Audit Pro',
    metaDescription: 'Scored 95 in Lighthouse but Search Console still says your site fails Core Web Vitals? Lab data and field data measure different things. Here\u2019s what actually counts for rankings.',
    keywords: ['PageSpeed Insights', 'lab data vs field data', 'Lighthouse score', 'CrUX', 'Core Web Vitals ranking'],
    category: 'PageSpeed',
    date: '2025-01-20',
    readTime: '6 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'A 95 Lighthouse score means almost nothing if your real users are on cheap phones with weak signal. Understanding the lab vs field split will save you months of confusion.',
    content: '',
  },
  {
    slug: 'eliminate-render-blocking-resources',
    title: 'Render-Blocking Resources: The Silent Killer of Your PageSpeed Score',
    metaTitle: 'How to Eliminate Render-Blocking Resources (CSS & JS) | SEO Audit Pro',
    metaDescription: 'That "eliminate render-blocking resources" warning in PageSpeed Insights costs most sites over a second of load time. Practical fixes for CSS, JavaScript and fonts.',
    keywords: ['render-blocking resources', 'critical CSS', 'defer JavaScript', 'eliminate render blocking', 'page speed optimization'],
    category: 'PageSpeed',
    date: '2024-12-30',
    readTime: '7 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'Your visitors stare at a white screen while the browser downloads stylesheets they mostly don\u2019t need yet. Here\u2019s how render-blocking works and how to break the logjam.',
    content: '',
  },
  {
    slug: 'image-optimization-seo-guide',
    title: 'Image Optimization for SEO: WebP, AVIF, and Lazy Loading Done Right',
    metaTitle: 'Image Optimization Guide: WebP, AVIF & Lazy Loading | SEO Audit Pro',
    metaDescription: 'Images are the heaviest thing on most pages. Learn modern formats, responsive srcset, correct lazy loading, and the mistakes that quietly destroy LCP scores.',
    keywords: ['image optimization', 'WebP', 'AVIF', 'lazy loading', 'image SEO', 'responsive images'],
    category: 'PageSpeed',
    date: '2024-12-12',
    readTime: '7 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'The average web page is mostly images by weight. Getting them right is the highest-leverage speed work most sites can do, and most sites are doing at least one part wrong.',
    content: '',
  },
];
