import type { BlogArticle } from './types';

export const articlesWordPress: BlogArticle[] = [
  {
    slug: 'wordpress-plugins-slowing-site',
    title: 'Your WordPress Plugins Are Killing Your SEO (Here\u2019s Proof)',
    metaTitle: 'WordPress Plugins Slowing Your Site? How to Find & Fix It | SEO Audit Pro',
    metaDescription: 'Every WordPress plugin adds weight, queries, or scripts. Learn how to measure exactly which plugins slow your site down and how to cut the bloat without losing features.',
    keywords: ['WordPress plugins slow', 'WordPress performance', 'plugin bloat', 'WordPress speed optimization', 'WordPress SEO'],
    category: 'WordPress SEO',
    date: '2025-01-16',
    readTime: '6 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'Forty-three active plugins is not a personality. It\u2019s a performance problem. Here\u2019s how to find out what each plugin actually costs you, with real numbers.',
    content: '',
  },
  {
    slug: 'wordpress-seo-setup-guide',
    title: 'WordPress SEO Setup: The Only Guide You Actually Need',
    metaTitle: 'WordPress SEO Setup Guide 2025: Step by Step | SEO Audit Pro',
    metaDescription: 'Permalinks, SEO plugins, sitemaps, schema, noindex traps and more. A complete, practical WordPress SEO configuration guide without the fluff or upsells.',
    keywords: ['WordPress SEO', 'WordPress SEO setup', 'Yoast settings', 'Rank Math setup', 'WordPress sitemap'],
    category: 'WordPress SEO',
    date: '2025-01-03',
    readTime: '7 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'Most WordPress SEO guides are 6,000 words of plugin screenshots. This is the distilled version: what to configure, what to skip, and the traps that quietly deindex sites.',
    content: '',
  },
  {
    slug: 'fix-slow-ttfb-wordpress',
    title: 'Slow TTFB on WordPress? Blame Your Hosting (and These 5 Things)',
    metaTitle: 'Fix Slow TTFB on WordPress: 5 Real Causes & Solutions | SEO Audit Pro',
    metaDescription: 'Time to First Byte over 800ms sabotages your LCP before the page even starts rendering. The five real causes of slow WordPress TTFB and how to fix each one.',
    keywords: ['TTFB WordPress', 'slow server response', 'WordPress hosting speed', 'reduce TTFB', 'WordPress caching'],
    category: 'WordPress SEO',
    date: '2024-12-22',
    readTime: '6 min read',
    author: 'SEO Audit Pro Team',
    excerpt: 'You can optimize images forever, but if your server takes 1.5 seconds to respond, your Core Web Vitals are doomed from the start. Let\u2019s fix the foundation.',
    content: '',
  },
];
